version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          CHANTS_DIR: /home/circleci/chants/BN_lat_1112_Sequences/musicxml
          CHANTSTATS_OUTPUT_ROOT_DIR: /tmp/analysis_results
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y tree
      - run: git clone https://github.com/maxalbert/chants.git /home/circleci/chants
      - run: PIPENV_PIPFILE=chantstats/Pipfile pipenv install --deploy --dev
      - run: cd chantstats && make test-all
      - store_artifacts:
          path: /tmp/analysis_results
          destination: analysis_results
