version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          CHANTS_DIR: /home/circleci/chants/
    steps:
      - checkout
      - run:
          name: "Export timestamp for this test run"
          command: echo "TIMESTAMP=$(date +%Y-%m-%d_%H.%M.%S)" > /tmp/env_timestamp.sh
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'source /tmp/env_timestamp.sh' >> $BASH_ENV
            echo 'export GIT_REV="$(echo $CIRCLE_SHA1 | cut -c -10)"' >> $BASH_ENV
            echo 'export TEST_RUN_ID="${TIMESTAMP}__${GIT_REV}"' >> $BASH_ENV
            echo 'export RESULTS_FOLDER_NAME="analysis_results__$TEST_RUN_ID"' >> $BASH_ENV
            echo 'export ZIP_FILE_NAME="analysis_results__$TEST_RUN_ID.zip"' >> $BASH_ENV
            echo 'export CHANTSTATS_OUTPUT_ROOT_DIR="/tmp/analysis_results/$RESULTS_FOLDER_NAME"' >> $BASH_ENV
      - run: sudo apt-get update && sudo apt-get install -y tree
      - run: git clone https://github.com/maxalbert/chants.git /home/circleci/chants
      - run: PIPENV_PIPFILE=chantstats/Pipfile pipenv install --deploy --dev
      - run:
          name: "Run unit tests"
          command: |
            cd chantstats
            pipenv run pytest --cov=chantstats --cov-report=term-missing -svx tests/v2/unit_tests/
      - run:
          name: "Run slow tests"
          command: |
            cd chantstats
            pipenv run pytest -svx --runslow --cov=chantstats --cov-report=term-missing tests/v2/calculate_and_export_results/ -k test_folder_structure_for_exported_results
          background: true
      - run:
          name: "Calculate and export results for plainchant sequences"
          command: |
            cd chantstats
            pipenv run python tests/v2/calculate_and_export_results/run_analyses_and_export_result.py plainchant_sequences
            touch .results-plainchant-sequences-done
          background: true

      - run:
          name: "Calculate and export results for responsorial chants, pc_freqs"
          command: |
            cd chantstats
            pipenv run python tests/v2/calculate_and_export_results/run_analyses_and_export_result.py responsorial_chants pc_freqs
            touch .results-responsorial-chants-1-done
          background: true
      - run:
          name: "Calculate and export results for responsorial chants, tendency"
          command: |
            cd chantstats
            pipenv run python tests/v2/calculate_and_export_results/run_analyses_and_export_result.py responsorial_chants tendency
            touch .results-responsorial-chants-2-done
          background: true
      - run:
          name: "Calculate and export results for responsorial chants, L&M"
          command: |
            cd chantstats
            pipenv run python tests/v2/calculate_and_export_results/run_analyses_and_export_result.py responsorial_chants L_and_M__L5_u_M5,L_and_M__L4_u_M4
            touch .results-responsorial-chants-3-done
          background: true

      - run:
          name: "Calculate and export results for organum pieces, pc_freqs"
          command: |
            cd chantstats
            pipenv run python tests/v2/calculate_and_export_results/run_analyses_and_export_result.py organum_pieces pc_freqs
            touch .results-organum-pieces-1-done
          background: true

      - run:
          name: "Calculate and export results for organum pieces, tendency"
          command: |
            cd chantstats
            pipenv run python tests/v2/calculate_and_export_results/run_analyses_and_export_result.py organum_pieces tendency
            touch .results-organum-pieces-2-done
          background: true

      - run:
          name: "Calculate and export results for organum pieces, L&M"
          command: |
            cd chantstats
            pipenv run python tests/v2/calculate_and_export_results/run_analyses_and_export_result.py organum_pieces L_and_M__L5_u_M5,L_and_M__L4_u_M4
            touch .results-organum-pieces-3-done
          background: true

      - run:
          name: Wait for calculation of results to complete
          command: |
            cd chantstats
            while [ ! -f ".results-plainchant-sequences-done" ] || [ ! -f ".results-responsorial-chants-1-done" ] || [ ! -f ".results-responsorial-chants-2-done" ] || [ ! -f ".results-responsorial-chants-3-done" ] || [ ! -f ".results-organum-pieces-1-done" ] || [ ! -f ".results-organum-pieces-2-done" ] || [ ! -f ".results-organum-pieces-3-done" ]; do
              echo "Waiting for calculation of results to complete"
              sleep 5
            done
      - run: cd /tmp/analysis_results/ && zip -r $ZIP_FILE_NAME $RESULTS_FOLDER_NAME
      - store_artifacts:
          path: /tmp/analysis_results
          destination: analysis_results
